# Prepare the policy fo the db-rw account
- !policy
  id: db-rw
  owner: !group ../owners
# Allow all application stakeholders to access it.
# More sensitive information will be filtered at variable ACL level
- !permit
  role: !group ../../all-members
  privileges: [read, execute]
  resource: !policy db-rw
# Prepare the policy fo the db-adm account
- !policy
  id: db-adm
  owner: !group ../owners
# Allow all application stakeholders to access it.
# More sensitive information will be filtered at variable ACL level
- !permit
  role: !group ../../all-members
  privileges: [read, execute]
  resource: !policy db-adm
